name: 页面部署流程

on:
  push:
    branches:
      - docusaurus
    # 由dream_pep撰写
    # 不要乱改流程内容

jobs:
  build:
    name: 构建 Docusaurus
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTION_ID: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: 安装 dependencies
        run: npm ci
      - name: 构建网页
        run: npm run build
      - name: 创建 metadata 文件夹
        run: echo "GITHUB_ACTION_ID=${{ github.run_id }}" > metadata.env
      - name: 上传 metadata 文件夹
        uses: actions/upload-artifact@v4
        with:
          name: metadata
          path: metadata.env

      - name: 上传后部署 Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    name: 构建页面到 GitHub Pages
    needs: build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: 构建页面到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
